spring.application.name=api

# Configuração dinâmica para funcionar em qualquer ambiente
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/pharmasw?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

USUARIO.NOME_PADRAO=admin
USUARIO.EMAIL_PADRAO=admin@admin.com
USUARIO.SENHA_PADRAO=12345

API.SECURITY.TOKEN.SECRET=${TOKEN_SECRET_PHARMASW}